In [1]:
import sys
sys.path.insert(0, "../")
sys.path

['../',
 '/workspaces/lets_build_gpt_video/experiments',
 '/opt/conda/lib/python310.zip',
 '/opt/conda/lib/python3.10',
 '/opt/conda/lib/python3.10/lib-dynload',
 '',
 '/opt/conda/lib/python3.10/site-packages',
 '/opt/conda/lib/python3.10/site-packages/PyYAML-6.0-py3.10-linux-x86_64.egg']

In [2]:
import torch
from torch.nn import functional

from src.text_processor import TextProcessor
from src.bigram import BiGram

/opt/conda/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
mytext = TextProcessor("shakespeare.txt")

In [4]:
model = BiGram(vocab_size=mytext.vocab_size)

# Text

In [4]:
mytext.vocab_size

65

In [5]:
mytext.all_chars

['\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [6]:
mytext.convert_string2integer("hello$")

[46, 43, 50, 50, 53, 3]

In [7]:
mytext.convert_integer2string([12,43,21,0,54])

'?eI\np'

In [ ]:
mytext.text

In [17]:
mytext.data

tensor([18, 47, 56,  ..., 45,  8,  0])

In [18]:
len(mytext.data)

1115394

In [19]:
mytext.data_val

tensor([12,  0,  0,  ..., 45,  8,  0])

In [20]:
x, y = mytext.get_batch(batch_size=1, block_size=1)
print(x.shape, y.shape)

torch.Size([1, 1]) torch.Size([1, 1])


In [21]:
for ii in range(0, 10, 2):
    print(ii)

0
2
4
6
8


In [22]:
len(mytext.data_train)

1003854

In [23]:
mytext.data_train[10:15]

tensor([64, 43, 52, 10,  0])

# Bigram model

In [25]:
model.loss(model(x), y)

tensor(3.4730, grad_fn=<NllLossBackward0>)

In [33]:
# Verify loss in the case batch_size=1, block_size=1
-(model(x).exp()/model(x).exp().sum())[0, 0, y].log()

tensor([[3.4730]], grad_fn=<NegBackward0>)

In [5]:
model.train(
    text=mytext,
    nb_epochs=10000,
    batch_size=32,
    block_size=8,
    learning_rate=1e-2,
    eval_interval = 100,
)

Epoch 0: train_loss = 142387.22477912903, eval_loss = 15782.818266153336
Epoch 100: train_loss = 113058.80290579796, eval_loss = 12558.0528216362
Epoch 200: train_loss = 96050.4090487957, eval_loss = 10684.946963310242
Epoch 300: train_loss = 87309.90303468704, eval_loss = 9732.457034111023
Epoch 400: train_loss = 83017.79263114929, eval_loss = 9263.11970114708
Epoch 500: train_loss = 80862.39229035378, eval_loss = 9042.427107691765
Epoch 600: train_loss = 79730.67677867413, eval_loss = 8924.10172855854
Epoch 700: train_loss = 79054.6739127636, eval_loss = 8860.580738782883
Epoch 800: train_loss = 78612.35302078724, eval_loss = 8811.885377883911
Epoch 900: train_loss = 78316.17607986927, eval_loss = 8782.898253917694
Epoch 1000: train_loss = 78114.66695129871, eval_loss = 8756.861783862114
Epoch 1100: train_loss = 77940.47797167301, eval_loss = 8738.118736982346
Epoch 1200: train_loss = 77824.57201373577, eval_loss = 8730.429413795471
Epoch 1300: train_loss = 77720.21132791042, eval_lo

In [6]:
model.inference(torch.tensor([0]))

/workspaces/lets_build_gpt_video/experiments/../src/bigram.py:27: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  probs = functional.softmax(logits)


tensor([18])

In [10]:
print(mytext.convert_integer2string(model.generate(1000, idx=torch.tensor([0]))))


ARDWh y an: ir aurt, d s es ES: y,
pitharapalloul INE: Wh fof mils sttar: blalackicher thivexpth s avan tr I o wen athare

A:
By sld he rn.
GUCEOfut th n.
Cos jurrme urd.
HEToven,
DUCHein t whastr o,
GESHERENou he falos
Whay he, Su fath! when PEd:
I's out honfrot brif a whesstis hirteid s Tht s, Bes thamagorouthonorter cef, matsu,

Me f h shastyof tot,
IV:
Ofond t rghalle? f t tive ste llu o aicr tt ly, d Ay, towakist toy hinghee mesothet h wnol s Heaclerimerethistle suny,
IZAnd inovestre, aly. the.

Coueimosem:
To IURUThatimyour, he is issemato hthoith.
Whone grube
cond t y VONENoo:
Ask,
Nodns hir, othe te onu cos y wh KELUENUS IUCHonoryovillearoufat!'llinom,

TUCAur.
AR:
YO: se t Ancks; by ayomanl faket he's yon mam sheais,-g; w, t! w-n, ishaye.
AROMyokitors whind h cer n at gr h tl.

TENVI quewighaveaca IG OFachilioodusp S:
TUCOUELAlld nch wo be dan, trde. t ghererabur ttowhid?
A:
RY asell!
T: thepr; ceers l oss gord igan ee an s t ard ts o te angr anesieshilesthate s thlllat omu! 